"""GraphQL SDL generator.

One object type per vertex set, one per hyperedge, and a Query root exposing
each. Hyperedges of arity greater than two become a type with one field per
endpoint rather than being flattened into a pair.
"""

from __future__ import annotations

from ..model import ResolvedModel
from ._naming import camel_case
from ._naming import endpoint_column_names
from ._naming import graphql_label_type
from ._naming import pascal_case


def generate_graphql(resolved: ResolvedModel) -> str:
    model = resolved.model
    lines: list[str] = []
    add = lines.append

    add(f"# GraphQL schema for system {model.name}")
    add("# Generated by knowledgework from a declared model. Do not edit by hand.")
    add("")

    for vertex_set in model.vertex_sets:
        add(f'"""Vertex set `{vertex_set.instance}`, declared with type {vertex_set.type_name}."""')
        add(f"type {pascal_case(vertex_set.type_name)} {{")
        add("  id: ID!")
        if vertex_set.label_type:
            add(f"  label: {graphql_label_type(vertex_set.label_type)}!")
        for declared in vertex_set.fields:
            nullability = "" if declared.optional else "!"
            add(
                f"  {camel_case(declared.name)}: "
                f"{graphql_label_type(declared.type_name)}{nullability}"
            )
        for edge_name in resolved.incidence.get(vertex_set.instance, ()):
            add(f"  {camel_case(edge_name)}: [{pascal_case(edge_name)}!]!")
        add("}")
        add("")

    for hyperedge in model.hyperedges:
        columns = [name.removesuffix("_id") for name in endpoint_column_names(resolved, hyperedge)]
        add(
            f'"""Hyperedge `{hyperedge.name}` of arity {hyperedge.arity}: '
            f"{' + '.join(hyperedge.connects)}.\"\"\""
        )
        if hyperedge.symmetric:
            left, right = hyperedge.symmetric
            add(
                f"# symmetric({left}, {right}): declared symmetric; "
                f"not enforced by this schema."
            )
        add(f"type {pascal_case(hyperedge.name)} {{")
        add("  id: ID!")
        for column, type_name in zip(columns, hyperedge.connects, strict=True):
            add(f"  {camel_case(column)}: {pascal_case(type_name)}!")
        for declared in hyperedge.fields:
            nullability = "" if declared.optional else "!"
            add(
                f"  {camel_case(declared.name)}: "
                f"{graphql_label_type(declared.type_name)}{nullability}"
            )
        add("}")
        add("")

    add("type Query {")
    for vertex_set in model.vertex_sets:
        type_name = pascal_case(vertex_set.type_name)
        add(f"  {camel_case(vertex_set.instance)}: [{type_name}!]!")
        add(f"  {camel_case(vertex_set.type_name)}ById(id: ID!): {type_name}")
    for hyperedge in model.hyperedges:
        add(f"  {camel_case(hyperedge.name)}: [{pascal_case(hyperedge.name)}!]!")
    add("}")
    add("")
    return "\n".join(lines)
