"""MongoDB generator: collections with real `$jsonSchema` validators.

The legacy generator emitted illustrative document literals that were neither
runnable nor validators. This emits `db.createCollection` calls carrying a
`$jsonSchema` the server actually enforces, plus the indexes implied by the
declared model.
"""

from __future__ import annotations

import json

from ..model import ResolvedModel
from ._naming import endpoint_column_names
from ._naming import json_label_type


def _validator(
    properties: dict[str, object],
    required: list[str],
    symmetric_fields: tuple[str, str] | None = None,
) -> str:
    """The collection validator, as a JSON literal.

    `$jsonSchema` describes one document at a time and cannot compare two of its
    fields, so a symmetric pair is enforced by combining it with `$expr` under an
    `$and`. The wrap is conditional: a collection with no symmetric pair emits
    the bare `$jsonSchema` it always did.
    """
    schema: dict[str, object] = {
        "$jsonSchema": {
            "bsonType": "object",
            "required": required,
            "properties": properties,
            "additionalProperties": True,
        }
    }
    if symmetric_fields is not None:
        left, right = symmetric_fields
        schema = {"$and": [schema, {"$expr": {"$lte": [f"${left}", f"${right}"]}}]}
    return json.dumps(schema, indent=2, sort_keys=False)


def generate_mongodb(resolved: ResolvedModel) -> str:
    model = resolved.model
    lines: list[str] = []
    add = lines.append

    add(f"// MongoDB schema for system {model.name}")
    add("// Generated by knowledgework from a declared model. Do not edit by hand.")
    add("// Run with: mongosh <connection-string> --file schema.mongodb.js")
    add("// This file is never executed by knowledgework itself.")
    add("")

    for vertex_set in model.vertex_sets:
        properties: dict[str, object] = {
            "_id": {"bsonType": "objectId"},
        }
        required = ["_id"]
        if vertex_set.label_type:
            properties["label"] = {
                "bsonType": json_label_type(vertex_set.label_type),
                "description": f"declared as `labeled {vertex_set.label_type}`",
            }
            required.append("label")
        for declared in vertex_set.fields:
            properties[declared.name] = {
                "bsonType": json_label_type(declared.type_name),
                "description": f"declared as `{declared.name}: {declared.type_name}`",
            }
            if not declared.optional:
                required.append(declared.name)
        add(f"// vertex set {vertex_set.instance} (type {vertex_set.type_name})")
        add(f'db.createCollection("{vertex_set.instance}", {{')
        add(f"  validator: {_validator(properties, required)},")
        add('  validationLevel: "strict",')
        add('  validationAction: "error"')
        add("});")
        if vertex_set.label_type:
            add(f'db.{vertex_set.instance}.createIndex({{ label: 1 }}, {{ unique: true }});')
        add("")

    for hyperedge in model.hyperedges:
        columns = [name.removesuffix("_id") for name in endpoint_column_names(resolved, hyperedge)]
        instances = resolved.endpoints[hyperedge.name]
        properties = {"_id": {"bsonType": "objectId"}}
        required = ["_id"]
        for column, instance in zip(columns, instances, strict=True):
            properties[column] = {
                "bsonType": "objectId",
                "description": f"reference into collection `{instance}`",
            }
            required.append(column)
        add(
            f"// hyperedge {hyperedge.name}: arity {hyperedge.arity}, "
            f"connects {' + '.join(hyperedge.connects)}"
        )
        for declared in hyperedge.fields:
            properties[declared.name] = {
                "bsonType": json_label_type(declared.type_name),
                "description": f"declared as `{declared.name}: {declared.type_name}`",
            }
            if not declared.optional:
                required.append(declared.name)
        symmetric_fields: tuple[str, str] | None = None
        if hyperedge.symmetric:
            left, right = hyperedge.symmetric
            symmetric_fields = (left, right)
            add(
                f"// symmetric({left}, {right}): enforced by $expr below. "
                f"A reversed pair is refused, not silently reordered."
            )
        add(f'db.createCollection("{hyperedge.name}", {{')
        add(f"  validator: {_validator(properties, required, symmetric_fields)},")
        add('  validationLevel: "strict",')
        add('  validationAction: "error"')
        add("});")
        index_spec = ", ".join(f"{column}: 1" for column in columns)
        add(f"db.{hyperedge.name}.createIndex({{ {index_spec} }}, {{ unique: true }});")
        add("")

    return "\n".join(lines)
