"""PostgreSQL DDL generator.

One table per declared vertex set, named after the vertex set's *instance*
name. One join table per hyperedge, with one foreign-key column per endpoint —
including for hyperedges of arity greater than two, which is the case a
relational schema normally cannot express without this step.
"""

from __future__ import annotations

from ..model import ResolvedModel
from ._naming import endpoint_column_names
from ._naming import sql_label_type


def generate_postgres(resolved: ResolvedModel) -> str:
    model = resolved.model
    lines: list[str] = []
    add = lines.append

    add(f"-- PostgreSQL schema for system {model.name}")
    add("-- Generated by knowledgework from a declared model. Do not edit by hand.")
    add("-- Deterministic output: no timestamp, no generated identifiers.")
    add("")
    add('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    add("")
    add("-- Vertex tables: one per declared vertex set.")

    for vertex_set in model.vertex_sets:
        add("")
        add(f"-- vertex set {vertex_set.instance} (type {vertex_set.type_name})")
        add(f"CREATE TABLE {vertex_set.instance} (")
        # (sql, trailing comment) so the comma lands before the comment, not inside it
        columns: list[tuple[str, str]] = [
            ("    id UUID PRIMARY KEY DEFAULT gen_random_uuid()", "")
        ]
        if vertex_set.label_type:
            column_type = sql_label_type(vertex_set.label_type)
            columns.append(
                (
                    f"    label {column_type} NOT NULL UNIQUE",
                    f"  -- declared: labeled {vertex_set.label_type}",
                )
            )
        else:
            columns.append(("    label TEXT", "  -- no `labeled` clause declared"))
        for declared in vertex_set.fields:
            nullability = "" if declared.optional else " NOT NULL"
            columns.append(
                (f"    {declared.name} {sql_label_type(declared.type_name)}{nullability}", "")
            )
        for index, (sql, comment) in enumerate(columns):
            separator = "," if index < len(columns) - 1 else ""
            add(f"{sql}{separator}{comment}")
        add(");")

    if model.hyperedges:
        add("")
        add("-- Hyperedge tables: one row per relationship instance.")
        add("-- Arity > 2 is represented directly, one foreign key per endpoint.")

    for hyperedge in model.hyperedges:
        columns = endpoint_column_names(resolved, hyperedge)
        instances = resolved.endpoints[hyperedge.name]
        add("")
        add(
            f"-- hyperedge {hyperedge.name}: arity {hyperedge.arity}, "
            f"connects {' + '.join(hyperedge.connects)}"
        )
        add(f"CREATE TABLE {hyperedge.name} (")
        add("    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
        for column, instance in zip(columns, instances, strict=True):
            add(f"    {column} UUID NOT NULL REFERENCES {instance}(id) ON DELETE CASCADE,")
        for declared in hyperedge.fields:
            nullability = "" if declared.optional else " NOT NULL"
            add(f"    {declared.name} {sql_label_type(declared.type_name)}{nullability},")
        table_constraints = [f"    UNIQUE ({', '.join(columns)})"]
        if hyperedge.symmetric:
            left, right = hyperedge.symmetric_columns()
            table_constraints.append(f"    CHECK ({left} <= {right})")
        add(",\n".join(table_constraints))
        add(");")
        if hyperedge.symmetric:
            left, right = hyperedge.symmetric
            add(
                f"-- symmetric({left}, {right}): rows are stored in canonical order. "
                f"A reversed pair is refused, not silently reordered."
            )
        for column in columns:
            add(f"CREATE INDEX {hyperedge.name}_{column}_idx ON {hyperedge.name} ({column});")

    add("")
    return "\n".join(lines) + "\n"
